// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNu_m8_zDytBTv1owYGX0mRKxPnNH7mM',
    appId: '1:514268542370:web:375e093ee5d4c66ec6aefb',
    messagingSenderId: '514268542370',
    projectId: 'infant-physiotherapy',
    authDomain: 'infant-physiotherapy.firebaseapp.com',
    storageBucket: 'infant-physiotherapy.appspot.com',
    measurementId: 'G-G51MS5SPRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA81b5NxLyPKSmZevQHFpuRRHT2CUaACuY',
    appId: '1:514268542370:android:7c5fef4cf8ab9ad1c6aefb',
    messagingSenderId: '514268542370',
    projectId: 'infant-physiotherapy',
    storageBucket: 'infant-physiotherapy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqztIa5WtP9Kh5MomErQBucqlC73UsePY',
    appId: '1:514268542370:ios:fa79c25a1ae14389c6aefb',
    messagingSenderId: '514268542370',
    projectId: 'infant-physiotherapy',
    storageBucket: 'infant-physiotherapy.appspot.com',
    iosBundleId: 'com.example.physiotherapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqztIa5WtP9Kh5MomErQBucqlC73UsePY',
    appId: '1:514268542370:ios:fa79c25a1ae14389c6aefb',
    messagingSenderId: '514268542370',
    projectId: 'infant-physiotherapy',
    storageBucket: 'infant-physiotherapy.appspot.com',
    iosBundleId: 'com.example.physiotherapy',
  );
}
